# wrangler.toml
name = "gemini-proxy-panel2"
main = "src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./public"

[observability]
enabled = true

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "1ba033338c7040c8853fffba06c194d1"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "bf8a6c18575f42e2bcffcd1b29dcdbcd"

